version: "3.3"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: 87378 # Your API HASH from my.telegram.org
      API_HASH: b0e26258b551f788d5c7c0055d63a874 # Your API ID from my.telegram.org
      BOT_TOKEN: 6684002644:AAGUUiTNq0OU2XSdEi2rHjgxWz2--8CZRvg # Bot token, get it from @BotFather 
      SESSION: # Pyrogram string session
      AUTH: 2054958935 # User ID of Bot owner
      FORCESUB: SpaceXV2RAY # Username name of public channel without using '@'
